spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: company_service
              uri: lb://COMPANY
              predicates:
                - Path=/companies/**
            - id: job_service
              uri: lb://JOBS-DEV
              predicates:
                - Path=/jobs/**
            - id: review_service
              uri: lb://REVIEW
              predicates:
                - Path=/reviews/**
            - id: eureka-server
              uri: http://service-registry:8761
              predicates:
                - Path=/eureka/main
              filters:
                - SetPath=/
            - id: eureka-server-static
              uri: http://service-registry:8761
              predicates:
                - Path=/eureka/**


# if you are using lb instead of Http, use service name for uri.
# http is good when only one instance of microservice is running.
# when multiple instances are running it should be load balanced.

server:
  port: 8084

eureka:
  client:
    service-url:
      default: http://service-registry:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO